author: Stephen A. Fuqua
title: "FlightNode: A Platform for Avian Conservation Monitoring"
description: "FlightNode: A Platform for Avian Conservation Monitoring"
url: https://flightnode.github.io


permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - footnotes
    - no_intra_emphasis
    - autolink
    - strikethrough

gems:
  - jeykll-sitemap